resilience4j:
  circuitBreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 2s
        .slow-call-rate-threshold: 50
    instances:
      items:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 4s
    instances:
      items:
        base-config: default